"""initial schema

Revision ID: 500e6e3fa5c4
Revises: 
Create Date: 2026-07-09 21:37:05.211792

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500e6e3fa5c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale_default', sa.String(length=8), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurants_slug'), ['slug'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name_de', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('color_hex', sa.String(length=9), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'key', name='uq_categories_restaurant_key')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('exit_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dedup_window_ms', sa.Integer(), nullable=False),
    sa.Column('dedup_strategy', sa.String(length=32), nullable=False),
    sa.CheckConstraint("dedup_strategy IN ('primary_wins', 'first_wins')", name='ck_exit_groups_strategy'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exit_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exit_groups_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('models_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('classes_json', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("kind IN ('pretrained', 'finetuned')", name='ck_models_registry_kind'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'name', 'version', name='uq_models_registry_owner_name_version')
    )
    with op.batch_alter_table('models_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_registry_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('started_ts', sa.Integer(), nullable=False),
    sa.Column('ended_ts', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('exit_group_id', sa.Integer(), nullable=True),
    sa.Column('is_primary_in_group', sa.Boolean(), nullable=False),
    sa.Column('target_fps', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint("source_type IN ('rtsp', 'usb', 'file')", name='ck_cameras_source_type'),
    sa.ForeignKeyConstraint(['exit_group_id'], ['exit_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models_registry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_exit_group_id'), ['exit_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cameras_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('counting_eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scenario', sa.String(length=200), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('ground_truth_path', sa.String(length=1000), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models_registry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counting_eval_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counting_eval_runs_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'name', name='uq_menu_items_restaurant_name')
    )
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('class_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_class_id', sa.Integer(), nullable=False),
    sa.Column('model_class_name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.CheckConstraint('(category_id IS NOT NULL) OR (menu_item_id IS NOT NULL)', name='ck_class_mappings_target'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models_registry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'model_class_id', 'restaurant_id', name='uq_class_mappings_model_class')
    )
    with op.batch_alter_table('class_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_mappings_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_mappings_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('data_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('from_ts', sa.Integer(), nullable=False),
    sa.Column('to_ts', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_gaps', schema=None) as batch_op:
        batch_op.create_index('ix_data_gaps_camera_from_ts', ['camera_id', 'from_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_gaps_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_gaps_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('count_directions', sa.String(length=16), nullable=False),
    sa.Column('min_track_age', sa.Integer(), nullable=False),
    sa.Column('hysteresis_px', sa.Integer(), nullable=False),
    sa.Column('cooldown_ms', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('x1 >= 0 AND x1 <= 1', name='ck_lines_x1'),
    sa.CheckConstraint('x2 >= 0 AND x2 <= 1', name='ck_lines_x2'),
    sa.CheckConstraint('y1 >= 0 AND y1 <= 1', name='ck_lines_y1'),
    sa.CheckConstraint('y2 >= 0 AND y2 <= 1', name='ck_lines_y2'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lines_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lines_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('raw_class_name', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.Column('anchor_x', sa.Float(), nullable=False),
    sa.Column('anchor_y', sa.Float(), nullable=False),
    sa.Column('snapshot_path', sa.String(length=1000), nullable=True),
    sa.Column('dedup_group_id', sa.String(length=26), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.CheckConstraint("direction IN ('out', 'in')", name='ck_events_direction'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_camera_ts', ['camera_id', 'ts'], unique=False)
        batch_op.create_index('ix_events_dedup_group', ['dedup_group_id'], unique=False)
        batch_op.create_index('ix_events_restaurant_canonical_ts', ['restaurant_id', 'is_canonical', 'ts'], unique=False)
        batch_op.create_index('ix_events_restaurant_ts', ['restaurant_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_session_id'))
        batch_op.drop_index('ix_events_restaurant_ts')
        batch_op.drop_index('ix_events_restaurant_canonical_ts')
        batch_op.drop_index('ix_events_dedup_group')
        batch_op.drop_index('ix_events_camera_ts')

    op.drop_table('events')
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lines_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_lines_camera_id'))

    op.drop_table('lines')
    with op.batch_alter_table('data_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_gaps_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_data_gaps_camera_id'))
        batch_op.drop_index('ix_data_gaps_camera_from_ts')

    op.drop_table('data_gaps')
    with op.batch_alter_table('class_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_mappings_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_class_mappings_model_id'))

    op.drop_table('class_mappings')
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_items_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_menu_items_category_id'))

    op.drop_table('menu_items')
    with op.batch_alter_table('counting_eval_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counting_eval_runs_restaurant_id'))

    op.drop_table('counting_eval_runs')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_cameras_exit_group_id'))

    op.drop_table('cameras')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_restaurant_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('models_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_registry_restaurant_id'))

    op.drop_table('models_registry')
    with op.batch_alter_table('exit_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exit_groups_restaurant_id'))

    op.drop_table('exit_groups')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_restaurant_id'))

    op.drop_table('categories')
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurants_slug'))

    op.drop_table('restaurants')
    # ### end Alembic commands ###
